server:
  port: 80
  compression:
    #启用压缩
    enabled: true
    #设置压缩支持的格式（默认支持text/html等，但不支持application/json）
    mime-types: application/json,text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
  error:
    #指定错误path
    path: /error

#暴露loggers,caches这几个endpoint
management:
  endpoints:
    web:
      exposure:
        include: health,info,loggers,caches,cachers

spring:
  application:
    name: redismanagerweb
  profiles: 
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #\u6570\u636e\u5e93\u8fde\u63a5
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/redisadmin?&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: root
    password: root
    initialSize: 10
    minIdle: 10
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 200
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true


#mybatis
mybatis:
  mapperLocations: classpath*:mapper/**/*Mapper.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  #\u652f\u6301\u901a\u8fc7 Mapper\u63a5\u53e3\u53c2\u6570\u6765\u4f20\u9012\u5206\u9875\u53c2\u6570\uff0c\u9ed8\u8ba4\u503cfalse\uff0c\u5206\u9875\u63d2\u4ef6\u4f1a\u4ece\u67e5\u8be2\u65b9\u6cd5\u7684\u53c2\u6570\u503c\u4e2d\uff0c\u81ea\u52a8\u6839\u636e\u4e0a\u9762 params \u914d\u7f6e\u7684\u5b57\u6bb5\u4e2d\u53d6\u503c\uff0c\u67e5\u627e\u5230\u5408\u9002\u7684\u503c\u65f6\u5c31\u4f1a\u81ea\u52a8\u5206\u9875
  supportMethodsArguments: true

rm:
  encrypt:
    #私钥
    privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJjmj40kDRGKIJMfxyWUawKwS8wlw41JZ8wd/9w3mYuhOLNGhOgt6YwMDjh7I1wpoV+rsX/7L6P5Z89gWyAW+upJFLtRRZ5qKHE6fj8kyAsQA3YuYG0hzRgSnYDSeEk52r0BZAK0/ailv70NI4bino/g3o3teg1PMRVOE34hExFVAgMBAAECgYBiebQg4gQstLqQJxpbAMD/BU58GCJfP9TDKNseGQ0iWd6r0BJPeyp80VLjW6OFeyZ8+JakZ8HiKQKMFHH8M/C7rm/DFFT/J5IsEHIJLnQUnmlUFh9mYaWgZJcGHI0GUpi2Qq3pXQ7LTCwIKbfQXfEdMSMdlXO4J+kOjitsQRu+AQJBANU80SAGvtRmjdIjvquzlxM+IAQyOR4B+liDIKh7Oiqz1Ux2vR7MNCSB0O9k0ccZf8Kh6x2UIpRiaKG4pZJnMYECQQC3kCsKFUOeXJkWt51oCRYzTuOZYux1gEXoGp0uWsI3mw7RY5zq6j48JAQ1RwsZb8FvQhJshTMnoaBiUy1X9WHVAkBSBBVPYyjM2zEbLUJuGiI2dYOs+YA8iXg3yR+rjdH+kLKuuVDeYp5/mCq7mSSSlr0sKEkdVFfEiOFDqpiMagKBAkEAjZGyn+QmckwYBV03GLVpWcjN385bb4OuZoOgFdAJWblMhFC/BK4DsX5VgIF6HfQCyzu52dggy7/rYemkXuHwwQJBAJWfv5OBUGrOqHybFdqsWJxhHy9ZFA6Ojm7H7+YAht9F1012fF3gZPgVg7FpoaQtbp0UF6ZF2EjYT5XI8sBaDhc=
    #公钥
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCY5o+NJA0RiiCTH8cllGsCsEvMJcONSWfMHf/cN5mLoTizRoToLemMDA44eyNcKaFfq7F/+y+j+WfPYFsgFvrqSRS7UUWeaihxOn4/JMgLEAN2LmBtIc0YEp2A0nhJOdq9AWQCtP2opb+9DSOG4p6P4N6N7XoNTzEVThN+IRMRVQIDAQAB
    #md5加盐
    md5Salt: 9d7456d3-fa98-42a3-9b44-fb2d5bd2d2ac
---
#\u5f00\u53d1\u73af\u5883
spring:
  profiles: local

  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    database: ${redis.database}

logging:
  level:
    root: info
    com.alibaba.druid: debug
    org.mybatis: debug
    org.apache.ibatis: debug
    com.mysql: debug
    com.tz.redismanager.dao.mapper: debug
    #显示JdbcTemplate的sql执行日志
    org.springframework.jdbc.core: debug
    org.springframework.jdbc.core.StatementCreatorUtils: trace
  path: /home/tz/Logs/redismanager

rm:
  config: classpath:config/config-local.properties
---
#\u5f00\u53d1\u73af\u5883    
spring:
  profiles: dev
  
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    database: ${redis.database}

logging:
  level: 
    root: info
    com.alibaba.druid: debug
    org.mybatis: debug
    org.apache.ibatis: debug
    com.mysql: debug
    com.tz.redismanager.dao.mapper: debug
  path: /home/tz/Logs/redismanager

rm:
  config: classpath:config/config-dev.properties
---
#\u6d4b\u8bd5\u73af\u5883      
spring:
  profiles: test
  
  redis:
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    database: ${redis.database}

logging:
  level: 
    root: info
  path: /home/tz/Logs/redismanager

rm:
  config: classpath:config/config-test.properties
---
#online\u73af\u5883      
spring:
  profiles: online

  redis:
    cluster:
       nodes: ${redis.cluster.nodes}
    password: ${redis.password}
    database: ${redis.database}

logging:
  level:
    root: info
    com.alibaba.druid: debug
    org.mybatis: debug
    org.apache.ibatis: debug
    com.mysql: debug
    com.tz.redismanager.dao.mapper: debug
  path: /home/tz/Logs/redismanager

rm:
  #config: file:/home/tz/Logs/redismanager/config-online.properties
  config: classpath:config/config-online.properties
